### ISSUE TITLE
File 'faxi_valaddr.v' is missing

### ISSUE THREAD

**Issue by jiegec** [ZipCPU/wb2axip#48]
I was running SymbiYosys over .sby scripts in the repo, and encountered this error:

```shell
$ sby -f wbm2axisp.sby
SBY 17:15:33 [wbm2axisp_cvr] Removing directory '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr'.
SBY 17:15:33 [wbm2axisp_cvr] Copy '/home/jiegec/wb2axip/rtl/wbm2axisp.v' to '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr/src/wbm2axisp.v'.
SBY 17:15:33 [wbm2axisp_cvr] Copy '/home/jiegec/wb2axip/rtl/skidbuffer.v' to '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr/src/skidbuffer.v'.
SBY 17:15:33 [wbm2axisp_cvr] Copy '/home/jiegec/wb2axip/bench/formal/faxi_master.v' to '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr/src/faxi_master.v'.
SBY 17:15:33 [wbm2axisp_cvr] Copy '/home/jiegec/wb2axip/bench/formal/faxi_addr.v' to '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr/src/faxi_addr.v'.
SBY 17:15:33 [wbm2axisp_cvr] Copy '/home/jiegec/wb2axip/bench/formal/faxi_valaddr.v' to '/home/jiegec/wb2axip/bench/formal/wbm2axisp_cvr/src/faxi_valaddr.v'.
Traceback (most recent call last):
  File "/home/jiegec/prefix/SymbiYosys/bin/sby", line 469, in <module>
    task_retcode = run_task(task)
  File "/home/jiegec/prefix/SymbiYosys/bin/sby", line 442, in run_task
    task.run(setupmode)
  File "/home/jiegec/prefix/SymbiYosys/bin/../share/yosys/python3/sby_core.py", line 683, in run
    self.copy_src()
  File "/home/jiegec/prefix/SymbiYosys/bin/../share/yosys/python3/sby_core.py", line 343, in copy_src
    copyfile(srcfile, dstfile)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'faxi_valaddr.v'
```

I could not find the missing file anywhere.

**Comment by ZipCPU** [comment]
The verification of  the AXI full components is kept in a non-public repository.  That's where faxi_valaddr.v (a file to formally validate AXI addressing) resides and also what [this note](https://github.com/ZipCPU/wb2axip/blob/c1e5ebad2f0e6263270de050a0e9c7e296c9f534/rtl/wbm2axisp.v#L555-L556) is referring to.  That repository is available for Patreon supporters.
